LOCAL_PATH := $(call my-dir)

PRIVATE_INCLUDE_PATH := $(LOCAL_PATH)/private_include
LOCAL_TEST_SOURCE_PATH := test
LOCAL_LIBS_PATH := libs

include $(CLEAR_VARS)
LOCAL_MODULE := qmi
LOCAL_SRC_FILES := $(LOCAL_LIBS_PATH)/$(TARGET_ARCH_ABI)/libqmi.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := qmi_cci
LOCAL_SRC_FILES := $(LOCAL_LIBS_PATH)/$(TARGET_ARCH_ABI)/libqmi_cci.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := qmiservices
LOCAL_SRC_FILES := $(LOCAL_LIBS_PATH)/$(TARGET_ARCH_ABI)/libqmiservices.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := qmi-nas-test
LOCAL_CFLAGS += -DFEATURE_DSS_LINUX_ANDROID
LOCAL_CFLAGS += -DFEATURE_QMI_ANDROID
LOCAL_C_INCLUDES += $(PRIVATE_INCLUDE_PATH)/qmi/inc
LOCAL_C_INCLUDES += $(PRIVATE_INCLUDE_PATH)/qmi/platform
LOCAL_C_INCLUDES += $(PRIVATE_INCLUDE_PATH)/qmi/services
LOCAL_C_INCLUDES += $(PRIVATE_INCLUDE_PATH)/qmi-framework/inc
LOCAL_SRC_FILES += $(LOCAL_TEST_SOURCE_PATH)/app.c
LOCAL_SHARED_LIBRARIES := qmi qmi_cci qmiservices
include $(BUILD_EXECUTABLE)
